import org.gradle.api.file.DuplicatesStrategy
import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.compose)
    alias(libs.plugins.jmh)
}

group = "com.vishalgupta.photoselector"
version = "1.8.0"

kotlin {
    jvmToolchain(17)
}

// The app reads its own version and the update-feed URL at runtime through a generated BuildConfig, so
// the `version` above stays the single source of truth instead of a hand-synced runtime constant. The
// feed is a static JSON hosted in the Homebrew tap repo (already write-access wired in release.yml);
// editing it there is the kill switch / staged-rollout control. A tiny codegen task — no plugin.
val updateManifestUrl = "https://raw.githubusercontent.com/vgupta98/homebrew-tap/main/rhenium/update-manifest.json"
val generateBuildConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildconfig")
    val versionValue = project.version.toString()
    inputs.property("version", versionValue)
    inputs.property("manifestUrl", updateManifestUrl)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("com/vishalgupta/photoselector")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildConfig.kt").writeText(
            buildString {
                appendLine("// Generated by the generateBuildConfig Gradle task from the project version. Do not edit.")
                appendLine("package com.vishalgupta.photoselector")
                appendLine()
                appendLine("object BuildConfig {")
                appendLine("    const val VERSION: String = \"$versionValue\"")
                appendLine("    const val UPDATE_MANIFEST_URL: String = \"$updateManifestUrl\"")
                appendLine("}")
            },
        )
    }
}

kotlin.sourceSets["main"].kotlin.srcDir(generateBuildConfig)

// Compose compiler stability reports. Off by default (zero build cost); enable
// with `-PcomposeReports=true` to dump *-composables.txt / *-classes.txt under
// build/compose_compiler/. Inspect those to spot a composable that can't skip
// or a param/class that turned unstable. See CLAUDE.md "Recomposition checks".
composeCompiler {
    if (project.findProperty("composeReports") == "true") {
        val dir = layout.buildDirectory.dir("compose_compiler")
        reportsDestination = dir
        metricsDestination = dir
    }
}

// Resolve the full, all-platforms ONNX Runtime artifact in isolation so we can repackage it.
// Kept out of the app's own classpaths - only `slimOnnxRuntime` consumes it.
val onnxRuntimeFull: Configuration by configurations.creating { isTransitive = false }

dependencies {
    onnxRuntimeFull(libs.onnxruntime)
}

// The published `onnxruntime` jar is a fat, all-platforms artifact (~89 MB): it bundles the
// Windows (.dll + a ~290 MB uncompressed .pdb), Linux (.so) and macOS (.dylib) native libraries
// plus macOS .dSYM debug bundles. jpackage rolls the whole jar into the DMG verbatim, so a
// macOS-only build shipped Windows/Linux binaries and debug symbols it can never load - which
// roughly doubled the DMG (103 MB -> 201 MB at v1.5.0). Repackage it keeping only the macOS
// runtime dylibs (both arches, so a single DMG runs on Intel and Apple Silicon) and dropping the
// rest. See CLAUDE.md "ONNX Runtime is a bundled native dependency".
val slimOnnxRuntime = tasks.register<Jar>("slimOnnxRuntime") {
    description = "Repackages the ONNX Runtime jar with only the macOS runtime libraries."
    archiveBaseName.set("onnxruntime-slim")
    destinationDirectory.set(layout.buildDirectory.dir("slim-libs"))
    from({ onnxRuntimeFull.map(::zipTree) })
    exclude(
        "ai/onnxruntime/native/win-x64/**",
        "ai/onnxruntime/native/linux-x64/**",
        "ai/onnxruntime/native/linux-aarch64/**",
    )
    // macOS debug symbols (~18 MB of DWARF) - never loaded at runtime.
    exclude("**/*.dSYM/**")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// The DMG bundles only the macOS dylibs (see `slimOnnxRuntime`), but the test job runs on Linux CI
// (.github/workflows/ci.yml), where OnnxEmbeddingModelTest loads the *real* native through ONNX
// Runtime. Repackage just the Linux natives - and only the natives, no `ai.onnxruntime.*` classes,
// so this doesn't collide with the slim jar already on the classpath - and put it on the test
// runtime classpath only. ONNX Runtime resolves its native from the classpath resource, so this
// keeps the integration test running on Linux without re-bloating the shipped app bundle.
val onnxRuntimeLinuxNatives = tasks.register<Jar>("onnxRuntimeLinuxNatives") {
    description = "Repackages only the Linux ONNX Runtime natives, for the Linux CI test classpath."
    archiveBaseName.set("onnxruntime-linux-natives")
    destinationDirectory.set(layout.buildDirectory.dir("slim-libs"))
    from({ onnxRuntimeFull.map(::zipTree) })
    include(
        "ai/onnxruntime/native/linux-x64/**",
        "ai/onnxruntime/native/linux-aarch64/**",
    )
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    implementation(compose.materialIconsExtended)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.swing)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.collections.immutable)

    // HEIC decode bridges into the macOS ImageIO/CoreGraphics system frameworks via JNA.
    // No native libs are bundled (system frameworks are loaded by name); JNA ships its own
    // jnidispatch. The decode path sits behind PhotoDecoder so a future Windows build adds
    // its own decoder rather than replacing this.
    implementation(libs.jna)

    // ONNX Runtime powers the learned visual-similarity embedder (OnnxEmbeddingModel). The model
    // blob itself ships as a resource. We depend on a slimmed repackaging of the runtime jar
    // (see `slimOnnxRuntime` below) rather than the published artifact: that fat jar carries the
    // native libs for every desktop platform plus debug symbols, none of which a macOS app loads.
    implementation(files(slimOnnxRuntime))

    testImplementation(kotlin("test"))
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.junit)
    testImplementation(compose.desktop.uiTestJUnit4)

    // OnnxEmbeddingModelTest runs the real native; on the Linux CI runner the slim jar has no Linux
    // dylib, so supply the Linux natives here (test runtime only - never bundled into the DMG).
    testRuntimeOnly(files(onnxRuntimeLinuxNatives))

    // JMH (perf benchmarks under `src/jmh/kotlin/`)
    jmh(libs.jmh.core)
    jmh(libs.jmh.annprocess)
    "kaptJmh"(libs.jmh.annprocess)
}

jmh {
    resultFormat = "JSON"
    resultsFile = layout.buildDirectory.file("jmh/results.json")
    includeTests = false
    // Skiko needs the Metal renderApi hint on macOS; the rest of the JVM args
    // mirror the production application config to keep numbers comparable.
    jvmArgsAppend = listOf(
        "-Dskiko.renderApi=METAL",
        "-Dapple.awt.application.appearance=system",
        "-Dfile.encoding=UTF-8",
    )
}

compose.desktop {
    application {
        mainClass = "com.vishalgupta.photoselector.MainKt"

        jvmArgs += listOf(
            "-Xmx2g",
            "-XX:MaxMetaspaceSize=256m",
            "-Dapple.awt.application.appearance=system",
            "-Dskiko.renderApi=METAL",
            "-Dfile.encoding=UTF-8",
        )

        // Minified release build (`./gradlew packageReleaseDmg`) tree-shakes dead
        // code across every bundled jar - the unused 99.9% of material-icons-extended,
        // plus the slack in Compose/kotlinx - off the DMG. Reflection/JNI/codegen
        // entry points that the shrinker can't see are kept in proguard-rules.pro.
        // obfuscate stays off so crash stack traces remain readable. See
        // CLAUDE.md "Release process" and proguard-rules.pro for the keeps.
        buildTypes.release.proguard {
            configurationFiles.from(project.file("proguard-rules.pro"))
            obfuscate.set(false)
            // Shrink-only. Optimization bought ~1 MB (1.4%) over tree-shaking alone
            // but adds the riskiest, least-validatable ProGuard passes - not worth it
            // when the win is dead-code elimination and the failure modes are runtime-only.
            optimize.set(false)
        }

        nativeDistributions {
            targetFormats(TargetFormat.Dmg)
            packageName = "Rhenium"
            packageVersion = project.version.toString()
            description = "Browse, favourite and export wedding photos."
            copyright = "Copyright (c) 2026 Vishal Gupta"
            // java.net.http backs the update checker's HttpClient (HttpUpdateRepository). jpackage
            // ships a trimmed jlink runtime with ONLY the modules listed here, so an omitted module
            // is a ClassNotFoundException at runtime in the packaged app (but not under ./gradlew run,
            // which uses the full JDK) — add the module whenever new code reaches into a fresh one.
            modules("java.desktop", "java.naming", "java.net.http", "jdk.unsupported")

            macOS {
                bundleID = "com.vishalgupta.rhenium"
                appCategory = "public.app-category.photography"
                iconFile.set(project.file("src/main/resources/icon/AppIcon.icns"))
            }
        }
    }
}
